// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyoDeviceListener.proto

package StrokeGeniusProto;

public final class MyoDeviceListener {
  private MyoDeviceListener() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface myoDeviceListenerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 timeStamp = 1;
    boolean hasTimeStamp();
    int getTimeStamp();
    
    // required .StrokeGeniusProto.Vector3 pose = 2;
    boolean hasPose();
    StrokeGeniusProto.Vector3.Vector3 getPose();
    StrokeGeniusProto.Vector3.Vector3OrBuilder getPoseOrBuilder();
    
    // required .StrokeGeniusProto.Vector3 orientationData = 3;
    boolean hasOrientationData();
    StrokeGeniusProto.Vector3.Vector3 getOrientationData();
    StrokeGeniusProto.Vector3.Vector3OrBuilder getOrientationDataOrBuilder();
    
    // required .StrokeGeniusProto.Vector3 acceleromaterData = 4;
    boolean hasAcceleromaterData();
    StrokeGeniusProto.Vector3.Vector3 getAcceleromaterData();
    StrokeGeniusProto.Vector3.Vector3OrBuilder getAcceleromaterDataOrBuilder();
    
    // required .StrokeGeniusProto.Vector3 gyroscopeData = 5;
    boolean hasGyroscopeData();
    StrokeGeniusProto.Vector3.Vector3 getGyroscopeData();
    StrokeGeniusProto.Vector3.Vector3OrBuilder getGyroscopeDataOrBuilder();
    
    // required int32 rssi = 6;
    boolean hasRssi();
    int getRssi();
    
    // required .StrokeGeniusProto.EMGData emgData = 7;
    boolean hasEmgData();
    StrokeGeniusProto.EMGData.EMGData getEmgData();
    StrokeGeniusProto.EMGData.EMGDataOrBuilder getEmgDataOrBuilder();
  }
  public static final class myoDeviceListener extends
      com.google.protobuf.GeneratedMessage
      implements myoDeviceListenerOrBuilder {
    // Use myoDeviceListener.newBuilder() to construct.
    private myoDeviceListener(Builder builder) {
      super(builder);
    }
    private myoDeviceListener(boolean noInit) {}
    
    private static final myoDeviceListener defaultInstance;
    public static myoDeviceListener getDefaultInstance() {
      return defaultInstance;
    }
    
    public myoDeviceListener getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StrokeGeniusProto.MyoDeviceListener.internal_static_StrokeGeniusProto_myoDeviceListener_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StrokeGeniusProto.MyoDeviceListener.internal_static_StrokeGeniusProto_myoDeviceListener_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 timeStamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timeStamp_;
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTimeStamp() {
      return timeStamp_;
    }
    
    // required .StrokeGeniusProto.Vector3 pose = 2;
    public static final int POSE_FIELD_NUMBER = 2;
    private StrokeGeniusProto.Vector3.Vector3 pose_;
    public boolean hasPose() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public StrokeGeniusProto.Vector3.Vector3 getPose() {
      return pose_;
    }
    public StrokeGeniusProto.Vector3.Vector3OrBuilder getPoseOrBuilder() {
      return pose_;
    }
    
    // required .StrokeGeniusProto.Vector3 orientationData = 3;
    public static final int ORIENTATIONDATA_FIELD_NUMBER = 3;
    private StrokeGeniusProto.Vector3.Vector3 orientationData_;
    public boolean hasOrientationData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public StrokeGeniusProto.Vector3.Vector3 getOrientationData() {
      return orientationData_;
    }
    public StrokeGeniusProto.Vector3.Vector3OrBuilder getOrientationDataOrBuilder() {
      return orientationData_;
    }
    
    // required .StrokeGeniusProto.Vector3 acceleromaterData = 4;
    public static final int ACCELEROMATERDATA_FIELD_NUMBER = 4;
    private StrokeGeniusProto.Vector3.Vector3 acceleromaterData_;
    public boolean hasAcceleromaterData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public StrokeGeniusProto.Vector3.Vector3 getAcceleromaterData() {
      return acceleromaterData_;
    }
    public StrokeGeniusProto.Vector3.Vector3OrBuilder getAcceleromaterDataOrBuilder() {
      return acceleromaterData_;
    }
    
    // required .StrokeGeniusProto.Vector3 gyroscopeData = 5;
    public static final int GYROSCOPEDATA_FIELD_NUMBER = 5;
    private StrokeGeniusProto.Vector3.Vector3 gyroscopeData_;
    public boolean hasGyroscopeData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public StrokeGeniusProto.Vector3.Vector3 getGyroscopeData() {
      return gyroscopeData_;
    }
    public StrokeGeniusProto.Vector3.Vector3OrBuilder getGyroscopeDataOrBuilder() {
      return gyroscopeData_;
    }
    
    // required int32 rssi = 6;
    public static final int RSSI_FIELD_NUMBER = 6;
    private int rssi_;
    public boolean hasRssi() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getRssi() {
      return rssi_;
    }
    
    // required .StrokeGeniusProto.EMGData emgData = 7;
    public static final int EMGDATA_FIELD_NUMBER = 7;
    private StrokeGeniusProto.EMGData.EMGData emgData_;
    public boolean hasEmgData() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public StrokeGeniusProto.EMGData.EMGData getEmgData() {
      return emgData_;
    }
    public StrokeGeniusProto.EMGData.EMGDataOrBuilder getEmgDataOrBuilder() {
      return emgData_;
    }
    
    private void initFields() {
      timeStamp_ = 0;
      pose_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
      orientationData_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
      acceleromaterData_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
      gyroscopeData_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
      rssi_ = 0;
      emgData_ = StrokeGeniusProto.EMGData.EMGData.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPose()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrientationData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAcceleromaterData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGyroscopeData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRssi()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmgData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPose().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getOrientationData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getAcceleromaterData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getGyroscopeData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, pose_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, orientationData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, acceleromaterData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, gyroscopeData_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, rssi_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, emgData_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, pose_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, orientationData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, acceleromaterData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, gyroscopeData_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, rssi_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, emgData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static StrokeGeniusProto.MyoDeviceListener.myoDeviceListener parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static StrokeGeniusProto.MyoDeviceListener.myoDeviceListener parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static StrokeGeniusProto.MyoDeviceListener.myoDeviceListener parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static StrokeGeniusProto.MyoDeviceListener.myoDeviceListener parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static StrokeGeniusProto.MyoDeviceListener.myoDeviceListener parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static StrokeGeniusProto.MyoDeviceListener.myoDeviceListener parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static StrokeGeniusProto.MyoDeviceListener.myoDeviceListener parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static StrokeGeniusProto.MyoDeviceListener.myoDeviceListener parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static StrokeGeniusProto.MyoDeviceListener.myoDeviceListener parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static StrokeGeniusProto.MyoDeviceListener.myoDeviceListener parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(StrokeGeniusProto.MyoDeviceListener.myoDeviceListener prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements StrokeGeniusProto.MyoDeviceListener.myoDeviceListenerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StrokeGeniusProto.MyoDeviceListener.internal_static_StrokeGeniusProto_myoDeviceListener_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StrokeGeniusProto.MyoDeviceListener.internal_static_StrokeGeniusProto_myoDeviceListener_fieldAccessorTable;
      }
      
      // Construct using StrokeGeniusProto.MyoDeviceListener.myoDeviceListener.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPoseFieldBuilder();
          getOrientationDataFieldBuilder();
          getAcceleromaterDataFieldBuilder();
          getGyroscopeDataFieldBuilder();
          getEmgDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timeStamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (poseBuilder_ == null) {
          pose_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
        } else {
          poseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (orientationDataBuilder_ == null) {
          orientationData_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
        } else {
          orientationDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (acceleromaterDataBuilder_ == null) {
          acceleromaterData_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
        } else {
          acceleromaterDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (gyroscopeDataBuilder_ == null) {
          gyroscopeData_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
        } else {
          gyroscopeDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        rssi_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (emgDataBuilder_ == null) {
          emgData_ = StrokeGeniusProto.EMGData.EMGData.getDefaultInstance();
        } else {
          emgDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StrokeGeniusProto.MyoDeviceListener.myoDeviceListener.getDescriptor();
      }
      
      public StrokeGeniusProto.MyoDeviceListener.myoDeviceListener getDefaultInstanceForType() {
        return StrokeGeniusProto.MyoDeviceListener.myoDeviceListener.getDefaultInstance();
      }
      
      public StrokeGeniusProto.MyoDeviceListener.myoDeviceListener build() {
        StrokeGeniusProto.MyoDeviceListener.myoDeviceListener result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private StrokeGeniusProto.MyoDeviceListener.myoDeviceListener buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        StrokeGeniusProto.MyoDeviceListener.myoDeviceListener result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public StrokeGeniusProto.MyoDeviceListener.myoDeviceListener buildPartial() {
        StrokeGeniusProto.MyoDeviceListener.myoDeviceListener result = new StrokeGeniusProto.MyoDeviceListener.myoDeviceListener(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (poseBuilder_ == null) {
          result.pose_ = pose_;
        } else {
          result.pose_ = poseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (orientationDataBuilder_ == null) {
          result.orientationData_ = orientationData_;
        } else {
          result.orientationData_ = orientationDataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (acceleromaterDataBuilder_ == null) {
          result.acceleromaterData_ = acceleromaterData_;
        } else {
          result.acceleromaterData_ = acceleromaterDataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (gyroscopeDataBuilder_ == null) {
          result.gyroscopeData_ = gyroscopeData_;
        } else {
          result.gyroscopeData_ = gyroscopeDataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.rssi_ = rssi_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (emgDataBuilder_ == null) {
          result.emgData_ = emgData_;
        } else {
          result.emgData_ = emgDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StrokeGeniusProto.MyoDeviceListener.myoDeviceListener) {
          return mergeFrom((StrokeGeniusProto.MyoDeviceListener.myoDeviceListener)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(StrokeGeniusProto.MyoDeviceListener.myoDeviceListener other) {
        if (other == StrokeGeniusProto.MyoDeviceListener.myoDeviceListener.getDefaultInstance()) return this;
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasPose()) {
          mergePose(other.getPose());
        }
        if (other.hasOrientationData()) {
          mergeOrientationData(other.getOrientationData());
        }
        if (other.hasAcceleromaterData()) {
          mergeAcceleromaterData(other.getAcceleromaterData());
        }
        if (other.hasGyroscopeData()) {
          mergeGyroscopeData(other.getGyroscopeData());
        }
        if (other.hasRssi()) {
          setRssi(other.getRssi());
        }
        if (other.hasEmgData()) {
          mergeEmgData(other.getEmgData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTimeStamp()) {
          
          return false;
        }
        if (!hasPose()) {
          
          return false;
        }
        if (!hasOrientationData()) {
          
          return false;
        }
        if (!hasAcceleromaterData()) {
          
          return false;
        }
        if (!hasGyroscopeData()) {
          
          return false;
        }
        if (!hasRssi()) {
          
          return false;
        }
        if (!hasEmgData()) {
          
          return false;
        }
        if (!getPose().isInitialized()) {
          
          return false;
        }
        if (!getOrientationData().isInitialized()) {
          
          return false;
        }
        if (!getAcceleromaterData().isInitialized()) {
          
          return false;
        }
        if (!getGyroscopeData().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timeStamp_ = input.readInt32();
              break;
            }
            case 18: {
              StrokeGeniusProto.Vector3.Vector3.Builder subBuilder = StrokeGeniusProto.Vector3.Vector3.newBuilder();
              if (hasPose()) {
                subBuilder.mergeFrom(getPose());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPose(subBuilder.buildPartial());
              break;
            }
            case 26: {
              StrokeGeniusProto.Vector3.Vector3.Builder subBuilder = StrokeGeniusProto.Vector3.Vector3.newBuilder();
              if (hasOrientationData()) {
                subBuilder.mergeFrom(getOrientationData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setOrientationData(subBuilder.buildPartial());
              break;
            }
            case 34: {
              StrokeGeniusProto.Vector3.Vector3.Builder subBuilder = StrokeGeniusProto.Vector3.Vector3.newBuilder();
              if (hasAcceleromaterData()) {
                subBuilder.mergeFrom(getAcceleromaterData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setAcceleromaterData(subBuilder.buildPartial());
              break;
            }
            case 42: {
              StrokeGeniusProto.Vector3.Vector3.Builder subBuilder = StrokeGeniusProto.Vector3.Vector3.newBuilder();
              if (hasGyroscopeData()) {
                subBuilder.mergeFrom(getGyroscopeData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGyroscopeData(subBuilder.buildPartial());
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              rssi_ = input.readInt32();
              break;
            }
            case 58: {
              StrokeGeniusProto.EMGData.EMGData.Builder subBuilder = StrokeGeniusProto.EMGData.EMGData.newBuilder();
              if (hasEmgData()) {
                subBuilder.mergeFrom(getEmgData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setEmgData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 timeStamp = 1;
      private int timeStamp_ ;
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTimeStamp() {
        return timeStamp_;
      }
      public Builder setTimeStamp(int value) {
        bitField0_ |= 0x00000001;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timeStamp_ = 0;
        onChanged();
        return this;
      }
      
      // required .StrokeGeniusProto.Vector3 pose = 2;
      private StrokeGeniusProto.Vector3.Vector3 pose_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          StrokeGeniusProto.Vector3.Vector3, StrokeGeniusProto.Vector3.Vector3.Builder, StrokeGeniusProto.Vector3.Vector3OrBuilder> poseBuilder_;
      public boolean hasPose() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public StrokeGeniusProto.Vector3.Vector3 getPose() {
        if (poseBuilder_ == null) {
          return pose_;
        } else {
          return poseBuilder_.getMessage();
        }
      }
      public Builder setPose(StrokeGeniusProto.Vector3.Vector3 value) {
        if (poseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pose_ = value;
          onChanged();
        } else {
          poseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setPose(
          StrokeGeniusProto.Vector3.Vector3.Builder builderForValue) {
        if (poseBuilder_ == null) {
          pose_ = builderForValue.build();
          onChanged();
        } else {
          poseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergePose(StrokeGeniusProto.Vector3.Vector3 value) {
        if (poseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              pose_ != StrokeGeniusProto.Vector3.Vector3.getDefaultInstance()) {
            pose_ =
              StrokeGeniusProto.Vector3.Vector3.newBuilder(pose_).mergeFrom(value).buildPartial();
          } else {
            pose_ = value;
          }
          onChanged();
        } else {
          poseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearPose() {
        if (poseBuilder_ == null) {
          pose_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
          onChanged();
        } else {
          poseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public StrokeGeniusProto.Vector3.Vector3.Builder getPoseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPoseFieldBuilder().getBuilder();
      }
      public StrokeGeniusProto.Vector3.Vector3OrBuilder getPoseOrBuilder() {
        if (poseBuilder_ != null) {
          return poseBuilder_.getMessageOrBuilder();
        } else {
          return pose_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          StrokeGeniusProto.Vector3.Vector3, StrokeGeniusProto.Vector3.Vector3.Builder, StrokeGeniusProto.Vector3.Vector3OrBuilder> 
          getPoseFieldBuilder() {
        if (poseBuilder_ == null) {
          poseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              StrokeGeniusProto.Vector3.Vector3, StrokeGeniusProto.Vector3.Vector3.Builder, StrokeGeniusProto.Vector3.Vector3OrBuilder>(
                  pose_,
                  getParentForChildren(),
                  isClean());
          pose_ = null;
        }
        return poseBuilder_;
      }
      
      // required .StrokeGeniusProto.Vector3 orientationData = 3;
      private StrokeGeniusProto.Vector3.Vector3 orientationData_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          StrokeGeniusProto.Vector3.Vector3, StrokeGeniusProto.Vector3.Vector3.Builder, StrokeGeniusProto.Vector3.Vector3OrBuilder> orientationDataBuilder_;
      public boolean hasOrientationData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public StrokeGeniusProto.Vector3.Vector3 getOrientationData() {
        if (orientationDataBuilder_ == null) {
          return orientationData_;
        } else {
          return orientationDataBuilder_.getMessage();
        }
      }
      public Builder setOrientationData(StrokeGeniusProto.Vector3.Vector3 value) {
        if (orientationDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          orientationData_ = value;
          onChanged();
        } else {
          orientationDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setOrientationData(
          StrokeGeniusProto.Vector3.Vector3.Builder builderForValue) {
        if (orientationDataBuilder_ == null) {
          orientationData_ = builderForValue.build();
          onChanged();
        } else {
          orientationDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeOrientationData(StrokeGeniusProto.Vector3.Vector3 value) {
        if (orientationDataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              orientationData_ != StrokeGeniusProto.Vector3.Vector3.getDefaultInstance()) {
            orientationData_ =
              StrokeGeniusProto.Vector3.Vector3.newBuilder(orientationData_).mergeFrom(value).buildPartial();
          } else {
            orientationData_ = value;
          }
          onChanged();
        } else {
          orientationDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearOrientationData() {
        if (orientationDataBuilder_ == null) {
          orientationData_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
          onChanged();
        } else {
          orientationDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public StrokeGeniusProto.Vector3.Vector3.Builder getOrientationDataBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getOrientationDataFieldBuilder().getBuilder();
      }
      public StrokeGeniusProto.Vector3.Vector3OrBuilder getOrientationDataOrBuilder() {
        if (orientationDataBuilder_ != null) {
          return orientationDataBuilder_.getMessageOrBuilder();
        } else {
          return orientationData_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          StrokeGeniusProto.Vector3.Vector3, StrokeGeniusProto.Vector3.Vector3.Builder, StrokeGeniusProto.Vector3.Vector3OrBuilder> 
          getOrientationDataFieldBuilder() {
        if (orientationDataBuilder_ == null) {
          orientationDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              StrokeGeniusProto.Vector3.Vector3, StrokeGeniusProto.Vector3.Vector3.Builder, StrokeGeniusProto.Vector3.Vector3OrBuilder>(
                  orientationData_,
                  getParentForChildren(),
                  isClean());
          orientationData_ = null;
        }
        return orientationDataBuilder_;
      }
      
      // required .StrokeGeniusProto.Vector3 acceleromaterData = 4;
      private StrokeGeniusProto.Vector3.Vector3 acceleromaterData_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          StrokeGeniusProto.Vector3.Vector3, StrokeGeniusProto.Vector3.Vector3.Builder, StrokeGeniusProto.Vector3.Vector3OrBuilder> acceleromaterDataBuilder_;
      public boolean hasAcceleromaterData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public StrokeGeniusProto.Vector3.Vector3 getAcceleromaterData() {
        if (acceleromaterDataBuilder_ == null) {
          return acceleromaterData_;
        } else {
          return acceleromaterDataBuilder_.getMessage();
        }
      }
      public Builder setAcceleromaterData(StrokeGeniusProto.Vector3.Vector3 value) {
        if (acceleromaterDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          acceleromaterData_ = value;
          onChanged();
        } else {
          acceleromaterDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setAcceleromaterData(
          StrokeGeniusProto.Vector3.Vector3.Builder builderForValue) {
        if (acceleromaterDataBuilder_ == null) {
          acceleromaterData_ = builderForValue.build();
          onChanged();
        } else {
          acceleromaterDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeAcceleromaterData(StrokeGeniusProto.Vector3.Vector3 value) {
        if (acceleromaterDataBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              acceleromaterData_ != StrokeGeniusProto.Vector3.Vector3.getDefaultInstance()) {
            acceleromaterData_ =
              StrokeGeniusProto.Vector3.Vector3.newBuilder(acceleromaterData_).mergeFrom(value).buildPartial();
          } else {
            acceleromaterData_ = value;
          }
          onChanged();
        } else {
          acceleromaterDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearAcceleromaterData() {
        if (acceleromaterDataBuilder_ == null) {
          acceleromaterData_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
          onChanged();
        } else {
          acceleromaterDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public StrokeGeniusProto.Vector3.Vector3.Builder getAcceleromaterDataBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getAcceleromaterDataFieldBuilder().getBuilder();
      }
      public StrokeGeniusProto.Vector3.Vector3OrBuilder getAcceleromaterDataOrBuilder() {
        if (acceleromaterDataBuilder_ != null) {
          return acceleromaterDataBuilder_.getMessageOrBuilder();
        } else {
          return acceleromaterData_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          StrokeGeniusProto.Vector3.Vector3, StrokeGeniusProto.Vector3.Vector3.Builder, StrokeGeniusProto.Vector3.Vector3OrBuilder> 
          getAcceleromaterDataFieldBuilder() {
        if (acceleromaterDataBuilder_ == null) {
          acceleromaterDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              StrokeGeniusProto.Vector3.Vector3, StrokeGeniusProto.Vector3.Vector3.Builder, StrokeGeniusProto.Vector3.Vector3OrBuilder>(
                  acceleromaterData_,
                  getParentForChildren(),
                  isClean());
          acceleromaterData_ = null;
        }
        return acceleromaterDataBuilder_;
      }
      
      // required .StrokeGeniusProto.Vector3 gyroscopeData = 5;
      private StrokeGeniusProto.Vector3.Vector3 gyroscopeData_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          StrokeGeniusProto.Vector3.Vector3, StrokeGeniusProto.Vector3.Vector3.Builder, StrokeGeniusProto.Vector3.Vector3OrBuilder> gyroscopeDataBuilder_;
      public boolean hasGyroscopeData() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public StrokeGeniusProto.Vector3.Vector3 getGyroscopeData() {
        if (gyroscopeDataBuilder_ == null) {
          return gyroscopeData_;
        } else {
          return gyroscopeDataBuilder_.getMessage();
        }
      }
      public Builder setGyroscopeData(StrokeGeniusProto.Vector3.Vector3 value) {
        if (gyroscopeDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gyroscopeData_ = value;
          onChanged();
        } else {
          gyroscopeDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setGyroscopeData(
          StrokeGeniusProto.Vector3.Vector3.Builder builderForValue) {
        if (gyroscopeDataBuilder_ == null) {
          gyroscopeData_ = builderForValue.build();
          onChanged();
        } else {
          gyroscopeDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeGyroscopeData(StrokeGeniusProto.Vector3.Vector3 value) {
        if (gyroscopeDataBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              gyroscopeData_ != StrokeGeniusProto.Vector3.Vector3.getDefaultInstance()) {
            gyroscopeData_ =
              StrokeGeniusProto.Vector3.Vector3.newBuilder(gyroscopeData_).mergeFrom(value).buildPartial();
          } else {
            gyroscopeData_ = value;
          }
          onChanged();
        } else {
          gyroscopeDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearGyroscopeData() {
        if (gyroscopeDataBuilder_ == null) {
          gyroscopeData_ = StrokeGeniusProto.Vector3.Vector3.getDefaultInstance();
          onChanged();
        } else {
          gyroscopeDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public StrokeGeniusProto.Vector3.Vector3.Builder getGyroscopeDataBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getGyroscopeDataFieldBuilder().getBuilder();
      }
      public StrokeGeniusProto.Vector3.Vector3OrBuilder getGyroscopeDataOrBuilder() {
        if (gyroscopeDataBuilder_ != null) {
          return gyroscopeDataBuilder_.getMessageOrBuilder();
        } else {
          return gyroscopeData_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          StrokeGeniusProto.Vector3.Vector3, StrokeGeniusProto.Vector3.Vector3.Builder, StrokeGeniusProto.Vector3.Vector3OrBuilder> 
          getGyroscopeDataFieldBuilder() {
        if (gyroscopeDataBuilder_ == null) {
          gyroscopeDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              StrokeGeniusProto.Vector3.Vector3, StrokeGeniusProto.Vector3.Vector3.Builder, StrokeGeniusProto.Vector3.Vector3OrBuilder>(
                  gyroscopeData_,
                  getParentForChildren(),
                  isClean());
          gyroscopeData_ = null;
        }
        return gyroscopeDataBuilder_;
      }
      
      // required int32 rssi = 6;
      private int rssi_ ;
      public boolean hasRssi() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getRssi() {
        return rssi_;
      }
      public Builder setRssi(int value) {
        bitField0_ |= 0x00000020;
        rssi_ = value;
        onChanged();
        return this;
      }
      public Builder clearRssi() {
        bitField0_ = (bitField0_ & ~0x00000020);
        rssi_ = 0;
        onChanged();
        return this;
      }
      
      // required .StrokeGeniusProto.EMGData emgData = 7;
      private StrokeGeniusProto.EMGData.EMGData emgData_ = StrokeGeniusProto.EMGData.EMGData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          StrokeGeniusProto.EMGData.EMGData, StrokeGeniusProto.EMGData.EMGData.Builder, StrokeGeniusProto.EMGData.EMGDataOrBuilder> emgDataBuilder_;
      public boolean hasEmgData() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public StrokeGeniusProto.EMGData.EMGData getEmgData() {
        if (emgDataBuilder_ == null) {
          return emgData_;
        } else {
          return emgDataBuilder_.getMessage();
        }
      }
      public Builder setEmgData(StrokeGeniusProto.EMGData.EMGData value) {
        if (emgDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          emgData_ = value;
          onChanged();
        } else {
          emgDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder setEmgData(
          StrokeGeniusProto.EMGData.EMGData.Builder builderForValue) {
        if (emgDataBuilder_ == null) {
          emgData_ = builderForValue.build();
          onChanged();
        } else {
          emgDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder mergeEmgData(StrokeGeniusProto.EMGData.EMGData value) {
        if (emgDataBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              emgData_ != StrokeGeniusProto.EMGData.EMGData.getDefaultInstance()) {
            emgData_ =
              StrokeGeniusProto.EMGData.EMGData.newBuilder(emgData_).mergeFrom(value).buildPartial();
          } else {
            emgData_ = value;
          }
          onChanged();
        } else {
          emgDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder clearEmgData() {
        if (emgDataBuilder_ == null) {
          emgData_ = StrokeGeniusProto.EMGData.EMGData.getDefaultInstance();
          onChanged();
        } else {
          emgDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      public StrokeGeniusProto.EMGData.EMGData.Builder getEmgDataBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getEmgDataFieldBuilder().getBuilder();
      }
      public StrokeGeniusProto.EMGData.EMGDataOrBuilder getEmgDataOrBuilder() {
        if (emgDataBuilder_ != null) {
          return emgDataBuilder_.getMessageOrBuilder();
        } else {
          return emgData_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          StrokeGeniusProto.EMGData.EMGData, StrokeGeniusProto.EMGData.EMGData.Builder, StrokeGeniusProto.EMGData.EMGDataOrBuilder> 
          getEmgDataFieldBuilder() {
        if (emgDataBuilder_ == null) {
          emgDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              StrokeGeniusProto.EMGData.EMGData, StrokeGeniusProto.EMGData.EMGData.Builder, StrokeGeniusProto.EMGData.EMGDataOrBuilder>(
                  emgData_,
                  getParentForChildren(),
                  isClean());
          emgData_ = null;
        }
        return emgDataBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:StrokeGeniusProto.myoDeviceListener)
    }
    
    static {
      defaultInstance = new myoDeviceListener(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:StrokeGeniusProto.myoDeviceListener)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StrokeGeniusProto_myoDeviceListener_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StrokeGeniusProto_myoDeviceListener_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027MyoDeviceListener.proto\022\021StrokeGeniusP" +
      "roto\032\rVector3.proto\032\020Quaternion.proto\032\rE" +
      "MGData.proto\"\252\002\n\021myoDeviceListener\022\021\n\tti" +
      "meStamp\030\001 \002(\005\022(\n\004pose\030\002 \002(\0132\032.StrokeGeni" +
      "usProto.Vector3\0223\n\017orientationData\030\003 \002(\013" +
      "2\032.StrokeGeniusProto.Vector3\0225\n\021accelero" +
      "materData\030\004 \002(\0132\032.StrokeGeniusProto.Vect" +
      "or3\0221\n\rgyroscopeData\030\005 \002(\0132\032.StrokeGeniu" +
      "sProto.Vector3\022\014\n\004rssi\030\006 \002(\005\022+\n\007emgData\030" +
      "\007 \002(\0132\032.StrokeGeniusProto.EMGData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_StrokeGeniusProto_myoDeviceListener_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_StrokeGeniusProto_myoDeviceListener_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StrokeGeniusProto_myoDeviceListener_descriptor,
              new java.lang.String[] { "TimeStamp", "Pose", "OrientationData", "AcceleromaterData", "GyroscopeData", "Rssi", "EmgData", },
              StrokeGeniusProto.MyoDeviceListener.myoDeviceListener.class,
              StrokeGeniusProto.MyoDeviceListener.myoDeviceListener.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          StrokeGeniusProto.Vector3.getDescriptor(),
          StrokeGeniusProto.Quaternion.getDescriptor(),
          StrokeGeniusProto.EMGData.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
