// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyoDeviceListener.proto

#ifndef PROTOBUF_MyoDeviceListener_2eproto__INCLUDED
#define PROTOBUF_MyoDeviceListener_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace StrokeGeniusProto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MyoDeviceListener_2eproto();
void protobuf_AssignDesc_MyoDeviceListener_2eproto();
void protobuf_ShutdownFile_MyoDeviceListener_2eproto();

class Vector3;
class myoDeviceListener;

// ===================================================================

class Vector3 : public ::google::protobuf::Message {
 public:
  Vector3();
  virtual ~Vector3();
  
  Vector3(const Vector3& from);
  
  inline Vector3& operator=(const Vector3& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector3& default_instance();
  
  void Swap(Vector3* other);
  
  // implements Message ----------------------------------------------
  
  Vector3* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Vector3& from);
  void MergeFrom(const Vector3& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);
  
  // required float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);
  
  // required float z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline float z() const;
  inline void set_z(float value);
  
  // required float magnitude = 4;
  inline bool has_magnitude() const;
  inline void clear_magnitude();
  static const int kMagnitudeFieldNumber = 4;
  inline float magnitude() const;
  inline void set_magnitude(float value);
  
  // @@protoc_insertion_point(class_scope:StrokeGeniusProto.Vector3)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  inline void set_has_magnitude();
  inline void clear_has_magnitude();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  float x_;
  float y_;
  float z_;
  float magnitude_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_MyoDeviceListener_2eproto();
  friend void protobuf_AssignDesc_MyoDeviceListener_2eproto();
  friend void protobuf_ShutdownFile_MyoDeviceListener_2eproto();
  
  void InitAsDefaultInstance();
  static Vector3* default_instance_;
};
// -------------------------------------------------------------------

class myoDeviceListener : public ::google::protobuf::Message {
 public:
  myoDeviceListener();
  virtual ~myoDeviceListener();
  
  myoDeviceListener(const myoDeviceListener& from);
  
  inline myoDeviceListener& operator=(const myoDeviceListener& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const myoDeviceListener& default_instance();
  
  void Swap(myoDeviceListener* other);
  
  // implements Message ----------------------------------------------
  
  myoDeviceListener* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const myoDeviceListener& from);
  void MergeFrom(const myoDeviceListener& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 timeStamp = 1;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimeStampFieldNumber = 1;
  inline ::google::protobuf::int32 timestamp() const;
  inline void set_timestamp(::google::protobuf::int32 value);
  
  // required .StrokeGeniusProto.Vector3 pose = 2;
  inline bool has_pose() const;
  inline void clear_pose();
  static const int kPoseFieldNumber = 2;
  inline const ::StrokeGeniusProto::Vector3& pose() const;
  inline ::StrokeGeniusProto::Vector3* mutable_pose();
  inline ::StrokeGeniusProto::Vector3* release_pose();
  
  // required .StrokeGeniusProto.Vector3 orientationData = 3;
  inline bool has_orientationdata() const;
  inline void clear_orientationdata();
  static const int kOrientationDataFieldNumber = 3;
  inline const ::StrokeGeniusProto::Vector3& orientationdata() const;
  inline ::StrokeGeniusProto::Vector3* mutable_orientationdata();
  inline ::StrokeGeniusProto::Vector3* release_orientationdata();
  
  // required .StrokeGeniusProto.Vector3 acceleromaterData = 4;
  inline bool has_acceleromaterdata() const;
  inline void clear_acceleromaterdata();
  static const int kAcceleromaterDataFieldNumber = 4;
  inline const ::StrokeGeniusProto::Vector3& acceleromaterdata() const;
  inline ::StrokeGeniusProto::Vector3* mutable_acceleromaterdata();
  inline ::StrokeGeniusProto::Vector3* release_acceleromaterdata();
  
  // required .StrokeGeniusProto.Vector3 gyroscopeData = 5;
  inline bool has_gyroscopedata() const;
  inline void clear_gyroscopedata();
  static const int kGyroscopeDataFieldNumber = 5;
  inline const ::StrokeGeniusProto::Vector3& gyroscopedata() const;
  inline ::StrokeGeniusProto::Vector3* mutable_gyroscopedata();
  inline ::StrokeGeniusProto::Vector3* release_gyroscopedata();
  
  // required int32 rssi = 6;
  inline bool has_rssi() const;
  inline void clear_rssi();
  static const int kRssiFieldNumber = 6;
  inline ::google::protobuf::int32 rssi() const;
  inline void set_rssi(::google::protobuf::int32 value);
  
  // repeated int32 sensorData = 7 [packed = true];
  inline int sensordata_size() const;
  inline void clear_sensordata();
  static const int kSensorDataFieldNumber = 7;
  inline ::google::protobuf::int32 sensordata(int index) const;
  inline void set_sensordata(int index, ::google::protobuf::int32 value);
  inline void add_sensordata(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      sensordata() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_sensordata();
  
  // @@protoc_insertion_point(class_scope:StrokeGeniusProto.myoDeviceListener)
 private:
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_pose();
  inline void clear_has_pose();
  inline void set_has_orientationdata();
  inline void clear_has_orientationdata();
  inline void set_has_acceleromaterdata();
  inline void clear_has_acceleromaterdata();
  inline void set_has_gyroscopedata();
  inline void clear_has_gyroscopedata();
  inline void set_has_rssi();
  inline void clear_has_rssi();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::StrokeGeniusProto::Vector3* pose_;
  ::StrokeGeniusProto::Vector3* orientationdata_;
  ::google::protobuf::int32 timestamp_;
  ::google::protobuf::int32 rssi_;
  ::StrokeGeniusProto::Vector3* acceleromaterdata_;
  ::StrokeGeniusProto::Vector3* gyroscopedata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > sensordata_;
  mutable int _sensordata_cached_byte_size_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];
  
  friend void  protobuf_AddDesc_MyoDeviceListener_2eproto();
  friend void protobuf_AssignDesc_MyoDeviceListener_2eproto();
  friend void protobuf_ShutdownFile_MyoDeviceListener_2eproto();
  
  void InitAsDefaultInstance();
  static myoDeviceListener* default_instance_;
};
// ===================================================================


// ===================================================================

// Vector3

// required float x = 1;
inline bool Vector3::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vector3::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vector3::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vector3::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Vector3::x() const {
  return x_;
}
inline void Vector3::set_x(float value) {
  set_has_x();
  x_ = value;
}

// required float y = 2;
inline bool Vector3::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vector3::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vector3::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vector3::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Vector3::y() const {
  return y_;
}
inline void Vector3::set_y(float value) {
  set_has_y();
  y_ = value;
}

// required float z = 3;
inline bool Vector3::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Vector3::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Vector3::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Vector3::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float Vector3::z() const {
  return z_;
}
inline void Vector3::set_z(float value) {
  set_has_z();
  z_ = value;
}

// required float magnitude = 4;
inline bool Vector3::has_magnitude() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Vector3::set_has_magnitude() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Vector3::clear_has_magnitude() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Vector3::clear_magnitude() {
  magnitude_ = 0;
  clear_has_magnitude();
}
inline float Vector3::magnitude() const {
  return magnitude_;
}
inline void Vector3::set_magnitude(float value) {
  set_has_magnitude();
  magnitude_ = value;
}

// -------------------------------------------------------------------

// myoDeviceListener

// required int32 timeStamp = 1;
inline bool myoDeviceListener::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void myoDeviceListener::set_has_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void myoDeviceListener::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void myoDeviceListener::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline ::google::protobuf::int32 myoDeviceListener::timestamp() const {
  return timestamp_;
}
inline void myoDeviceListener::set_timestamp(::google::protobuf::int32 value) {
  set_has_timestamp();
  timestamp_ = value;
}

// required .StrokeGeniusProto.Vector3 pose = 2;
inline bool myoDeviceListener::has_pose() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void myoDeviceListener::set_has_pose() {
  _has_bits_[0] |= 0x00000002u;
}
inline void myoDeviceListener::clear_has_pose() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void myoDeviceListener::clear_pose() {
  if (pose_ != NULL) pose_->::StrokeGeniusProto::Vector3::Clear();
  clear_has_pose();
}
inline const ::StrokeGeniusProto::Vector3& myoDeviceListener::pose() const {
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
inline ::StrokeGeniusProto::Vector3* myoDeviceListener::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) pose_ = new ::StrokeGeniusProto::Vector3;
  return pose_;
}
inline ::StrokeGeniusProto::Vector3* myoDeviceListener::release_pose() {
  clear_has_pose();
  ::StrokeGeniusProto::Vector3* temp = pose_;
  pose_ = NULL;
  return temp;
}

// required .StrokeGeniusProto.Vector3 orientationData = 3;
inline bool myoDeviceListener::has_orientationdata() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void myoDeviceListener::set_has_orientationdata() {
  _has_bits_[0] |= 0x00000004u;
}
inline void myoDeviceListener::clear_has_orientationdata() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void myoDeviceListener::clear_orientationdata() {
  if (orientationdata_ != NULL) orientationdata_->::StrokeGeniusProto::Vector3::Clear();
  clear_has_orientationdata();
}
inline const ::StrokeGeniusProto::Vector3& myoDeviceListener::orientationdata() const {
  return orientationdata_ != NULL ? *orientationdata_ : *default_instance_->orientationdata_;
}
inline ::StrokeGeniusProto::Vector3* myoDeviceListener::mutable_orientationdata() {
  set_has_orientationdata();
  if (orientationdata_ == NULL) orientationdata_ = new ::StrokeGeniusProto::Vector3;
  return orientationdata_;
}
inline ::StrokeGeniusProto::Vector3* myoDeviceListener::release_orientationdata() {
  clear_has_orientationdata();
  ::StrokeGeniusProto::Vector3* temp = orientationdata_;
  orientationdata_ = NULL;
  return temp;
}

// required .StrokeGeniusProto.Vector3 acceleromaterData = 4;
inline bool myoDeviceListener::has_acceleromaterdata() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void myoDeviceListener::set_has_acceleromaterdata() {
  _has_bits_[0] |= 0x00000008u;
}
inline void myoDeviceListener::clear_has_acceleromaterdata() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void myoDeviceListener::clear_acceleromaterdata() {
  if (acceleromaterdata_ != NULL) acceleromaterdata_->::StrokeGeniusProto::Vector3::Clear();
  clear_has_acceleromaterdata();
}
inline const ::StrokeGeniusProto::Vector3& myoDeviceListener::acceleromaterdata() const {
  return acceleromaterdata_ != NULL ? *acceleromaterdata_ : *default_instance_->acceleromaterdata_;
}
inline ::StrokeGeniusProto::Vector3* myoDeviceListener::mutable_acceleromaterdata() {
  set_has_acceleromaterdata();
  if (acceleromaterdata_ == NULL) acceleromaterdata_ = new ::StrokeGeniusProto::Vector3;
  return acceleromaterdata_;
}
inline ::StrokeGeniusProto::Vector3* myoDeviceListener::release_acceleromaterdata() {
  clear_has_acceleromaterdata();
  ::StrokeGeniusProto::Vector3* temp = acceleromaterdata_;
  acceleromaterdata_ = NULL;
  return temp;
}

// required .StrokeGeniusProto.Vector3 gyroscopeData = 5;
inline bool myoDeviceListener::has_gyroscopedata() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void myoDeviceListener::set_has_gyroscopedata() {
  _has_bits_[0] |= 0x00000010u;
}
inline void myoDeviceListener::clear_has_gyroscopedata() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void myoDeviceListener::clear_gyroscopedata() {
  if (gyroscopedata_ != NULL) gyroscopedata_->::StrokeGeniusProto::Vector3::Clear();
  clear_has_gyroscopedata();
}
inline const ::StrokeGeniusProto::Vector3& myoDeviceListener::gyroscopedata() const {
  return gyroscopedata_ != NULL ? *gyroscopedata_ : *default_instance_->gyroscopedata_;
}
inline ::StrokeGeniusProto::Vector3* myoDeviceListener::mutable_gyroscopedata() {
  set_has_gyroscopedata();
  if (gyroscopedata_ == NULL) gyroscopedata_ = new ::StrokeGeniusProto::Vector3;
  return gyroscopedata_;
}
inline ::StrokeGeniusProto::Vector3* myoDeviceListener::release_gyroscopedata() {
  clear_has_gyroscopedata();
  ::StrokeGeniusProto::Vector3* temp = gyroscopedata_;
  gyroscopedata_ = NULL;
  return temp;
}

// required int32 rssi = 6;
inline bool myoDeviceListener::has_rssi() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void myoDeviceListener::set_has_rssi() {
  _has_bits_[0] |= 0x00000020u;
}
inline void myoDeviceListener::clear_has_rssi() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void myoDeviceListener::clear_rssi() {
  rssi_ = 0;
  clear_has_rssi();
}
inline ::google::protobuf::int32 myoDeviceListener::rssi() const {
  return rssi_;
}
inline void myoDeviceListener::set_rssi(::google::protobuf::int32 value) {
  set_has_rssi();
  rssi_ = value;
}

// repeated int32 sensorData = 7 [packed = true];
inline int myoDeviceListener::sensordata_size() const {
  return sensordata_.size();
}
inline void myoDeviceListener::clear_sensordata() {
  sensordata_.Clear();
}
inline ::google::protobuf::int32 myoDeviceListener::sensordata(int index) const {
  return sensordata_.Get(index);
}
inline void myoDeviceListener::set_sensordata(int index, ::google::protobuf::int32 value) {
  sensordata_.Set(index, value);
}
inline void myoDeviceListener::add_sensordata(::google::protobuf::int32 value) {
  sensordata_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
myoDeviceListener::sensordata() const {
  return sensordata_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
myoDeviceListener::mutable_sensordata() {
  return &sensordata_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace StrokeGeniusProto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MyoDeviceListener_2eproto__INCLUDED
